project_id = "lcpmqnkorcsclmpfbizr"

[functions.fake-news-monitor]
verify_jwt = false

[functions.fake-news-respond]
verify_jwt = false

[functions.fact-check-content]
verify_jwt = false

[functions.collect-signals]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-campaign]
verify_jwt = false

[functions.analyze-repercussion]
verify_jwt = false

[functions.analyze-crisis]
verify_jwt = false

[functions.generate-video]
verify_jwt = false